### PR TITLE
Extend support for apple devices

### PR DESCRIPTION
**Pull request by hansegucker**
Add option to specify special icons for apple devices because icons on apple devices are tailored to size differently

### CODE REVIEW

**Comment by hansegucker** [comment]
@silviolleite What is the current status? Is there any feedback?

**Comment by silviolleite** [comment]
Great job!

**Comment by silviolleite** [comment]
> @silviolleite What is the current status? Is there any feedback?

@hansegucker. I am sorry, I was on vacation ;)

**Comment by hansegucker** [comment]
Thank you!

**Pull request merged**
